spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pli_please
    driver-class-name: org.postgresql.Driver
    username: pli_please
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user-read-email
              - playlist-read-private
              - playlist-read-collaborative
            client-name: spotify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

jwt:
  secret-b64: ${JWT_SECRET_B64:}
  expiration: 86400000
  refresh-expiration: 604800000

server:
  port: 8080

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}